language: python
python:
  - "2.7"

install:
  # 在CI服务器上安装集成测试工具
  - pip install nose


script:
  # 安装依赖
  - pip install -r requirements.txt
  # 编译Python C扩展
  - python setup.py build_ext
  # 安装Hamaa
  - pip install .
  # 跑测试并检测代码覆盖率
  - nosetests -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
