site_name: Hamaa中文文档
docs_dir: .
theme: readthedocs
repo_url: http://github.com/monitor1379/hamaa-docs-zn
site_url: http://www.monitor1379.com


pages:
- 主页: index.md
- 快速开始: getting_started.md
- 模型: models.md
- 网络层: layers.md
- 优化器: optimizers.md
- 关于: about.md
